### PR TITLE
Experiment with Costas Loop

### PR DESCRIPTION
**Pull request by srsampson**
I pulled in some code from GNU radio project. The alpha, beta, min, max are just guesses for now.

It doesn't track very well with the current settings, but you can see the constellation with a 1 Hz freq error, whereas without the costas, it is just noise.

### CODE REVIEW

**Comment by drowe67** [comment]
@srsampson so you've decided to go with a feedback phase recovery/freq tracking scheme?  That means you won't need pilot symbols (just a unique word for frame sync/phase ambiguity resolution perhaps), but I think also means it will need a continuous signal (rather than bursts) to sync up.

**Comment by srsampson** [comment]
I guess I should say that curiosity killed the kat. I was interested in seeing how it worked, but try as I might, I never did get it to dampen with various alpha and beta.

Put it down as a deviation from the path.

**Comment by srsampson** [comment]
I do think of the voice mode as continuous though.

**Comment by srsampson** [comment]
Experiment to see if pilot window correlation can be used for a timing estimate.

scatter

**Comment by srsampson** [comment]
Interesting that changing from a 35% to a 50% rolloff on FIR filter, the timing estimate syncs but the scatter diagram looks terrible.

**Comment by drowe67** [comment]
There's probably quite a few ways to do timing, but I've only used the non-linearity + single point DFT method.

**Comment by srsampson** [comment]
I played with it today, and I don't think the method is very good. It takes too long to sync. For example it will read 10, 10, 8... or two frames before arriving at the correct index.

**Comment by drowe67** [comment]
The non-linearity methods usually work with a window of 50 or so symbols, i.e. a decent fine timing estimate over a typical frame.  If you get stuck let me know and I have a go at a fine timing estimator some time.

**Pull request closed without merging**
